/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#ifdef HAVE_UNISTD_H
#include <unistd.h>
#endif
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *vbox1;
  GtkWidget *imagen;
  GtkWidget *hbox1;
  GtkWidget *vbox2;
  GtkWidget *histograma;
  GtkWidget *muestra;
  GtkWidget *fixed1;
  GtkObject *numeroResultado_adj;
  GtkWidget *numeroResultado;
  GtkObject *minimo_adj;
  GtkWidget *minimo;
  GtkObject *umbral_adj;
  GtkWidget *umbral;
  GtkWidget *verOriginal;
  GSList *verOriginal_group = NULL;
  GtkWidget *verResultados;
  GtkWidget *vseparator1;
  GtkWidget *vseparator2;
  GtkWidget *hseparator2;
  GtkWidget *matiz;
  GSList *matiz_group = NULL;
  GtkWidget *saturacion;
  GtkWidget *valor;
  GtkObject *valorMaximo_adj;
  GtkWidget *valorMaximo;
  GtkWidget *hseparator1;
  GtkWidget *procesar;
  GtkWidget *selectorArchivo;
  GtkObject *resolucion_adj;
  GtkWidget *resolucion;
  GtkWidget *separar;
  GtkWidget *label3;
  GtkWidget *label2;
  GtkWidget *comboColores;
  GtkWidget *borrarMaximo;
  GtkWidget *label1;
  GtkWidget *label4;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("Proyecto PDI Yícas"));

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (window1), vbox1);

  imagen = create_pixmap (window1, NULL);
  gtk_widget_show (imagen);
  gtk_box_pack_start (GTK_BOX (vbox1), imagen, TRUE, TRUE, 0);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, TRUE, TRUE, 0);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (hbox1), vbox2, TRUE, TRUE, 0);

  histograma = gtk_drawing_area_new ();
  gtk_widget_show (histograma);
  gtk_box_pack_start (GTK_BOX (vbox2), histograma, TRUE, TRUE, 0);
  gtk_widget_set_size_request (histograma, 360, 100);

  muestra = gtk_drawing_area_new ();
  gtk_widget_show (muestra);
  gtk_box_pack_start (GTK_BOX (vbox2), muestra, TRUE, TRUE, 0);
  gtk_widget_set_size_request (muestra, 360, 10);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_box_pack_start (GTK_BOX (hbox1), fixed1, TRUE, TRUE, 0);

  numeroResultado_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  numeroResultado = gtk_spin_button_new (GTK_ADJUSTMENT (numeroResultado_adj), 1, 0);
  gtk_widget_show (numeroResultado);
  gtk_fixed_put (GTK_FIXED (fixed1), numeroResultado, 176, 8);
  gtk_widget_set_size_request (numeroResultado, 40, 24);
  gtk_widget_set_sensitive (numeroResultado, FALSE);

  minimo_adj = gtk_adjustment_new (10, 0, 100, 1, 10, 10);
  minimo = gtk_spin_button_new (GTK_ADJUSTMENT (minimo_adj), 1, 0);
  gtk_widget_show (minimo);
  gtk_fixed_put (GTK_FIXED (fixed1), minimo, 56, 120);
  gtk_widget_set_size_request (minimo, 40, 24);

  umbral_adj = gtk_adjustment_new (20, 0, 359, 1, 10, 10);
  umbral = gtk_spin_button_new (GTK_ADJUSTMENT (umbral_adj), 1, 0);
  gtk_widget_show (umbral);
  gtk_fixed_put (GTK_FIXED (fixed1), umbral, 160, 224);
  gtk_widget_set_size_request (umbral, 40, 24);

  verOriginal = gtk_radio_button_new_with_mnemonic (NULL, _("Original"));
  gtk_widget_show (verOriginal);
  gtk_fixed_put (GTK_FIXED (fixed1), verOriginal, 8, 8);
  gtk_widget_set_size_request (verOriginal, 106, 22);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (verOriginal), verOriginal_group);
  verOriginal_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (verOriginal));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (verOriginal), TRUE);

  verResultados = gtk_radio_button_new_with_mnemonic (NULL, _("Resultado"));
  gtk_widget_show (verResultados);
  gtk_fixed_put (GTK_FIXED (fixed1), verResultados, 88, 8);
  gtk_widget_set_size_request (verResultados, 88, 24);
  gtk_widget_set_sensitive (verResultados, FALSE);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (verResultados), verOriginal_group);
  verOriginal_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (verResultados));

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_fixed_put (GTK_FIXED (fixed1), vseparator1, 104, 80);
  gtk_widget_set_size_request (vseparator1, 16, 73);

  vseparator2 = gtk_vseparator_new ();
  gtk_widget_show (vseparator2);
  gtk_fixed_put (GTK_FIXED (fixed1), vseparator2, 200, 80);
  gtk_widget_set_size_request (vseparator2, 16, 73);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_fixed_put (GTK_FIXED (fixed1), hseparator2, 112, 72);
  gtk_widget_set_size_request (hseparator2, 97, 16);

  matiz = gtk_radio_button_new_with_mnemonic (NULL, _("Matiz"));
  gtk_widget_show (matiz);
  gtk_fixed_put (GTK_FIXED (fixed1), matiz, 112, 80);
  gtk_widget_set_size_request (matiz, 96, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (matiz), matiz_group);
  matiz_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (matiz));

  saturacion = gtk_radio_button_new_with_mnemonic (NULL, _("Saturacion"));
  gtk_widget_show (saturacion);
  gtk_fixed_put (GTK_FIXED (fixed1), saturacion, 112, 104);
  gtk_widget_set_size_request (saturacion, 106, 22);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (saturacion), matiz_group);
  matiz_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (saturacion));

  valor = gtk_radio_button_new_with_mnemonic (NULL, _("Valor"));
  gtk_widget_show (valor);
  gtk_fixed_put (GTK_FIXED (fixed1), valor, 112, 128);
  gtk_widget_set_size_request (valor, 88, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (valor), matiz_group);
  matiz_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (valor));

  valorMaximo_adj = gtk_adjustment_new (0, 0, 359, 1, 10, 10);
  valorMaximo = gtk_spin_button_new (GTK_ADJUSTMENT (valorMaximo_adj), 1, 0);
  gtk_widget_show (valorMaximo);
  gtk_fixed_put (GTK_FIXED (fixed1), valorMaximo, 56, 224);
  gtk_widget_set_size_request (valorMaximo, 40, 24);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_fixed_put (GTK_FIXED (fixed1), hseparator1, 111, 145);
  gtk_widget_set_size_request (hseparator1, 97, 16);

  procesar = gtk_button_new_with_mnemonic (_("Analizar"));
  gtk_widget_show (procesar);
  gtk_fixed_put (GTK_FIXED (fixed1), procesar, 8, 80);
  gtk_widget_set_size_request (procesar, 96, 32);
  gtk_widget_set_sensitive (procesar, FALSE);

  selectorArchivo = gtk_file_chooser_button_new (_("Seleccione un archivo"), GTK_FILE_CHOOSER_ACTION_OPEN);
  gtk_widget_show (selectorArchivo);
  gtk_fixed_put (GTK_FIXED (fixed1), selectorArchivo, 8, 40);
  gtk_widget_set_size_request (selectorArchivo, 208, 32);

  resolucion_adj = gtk_adjustment_new (10, 1, 100, 1, 10, 10);
  resolucion = gtk_spin_button_new (GTK_ADJUSTMENT (resolucion_adj), 1, 0);
  gtk_widget_show (resolucion);
  gtk_fixed_put (GTK_FIXED (fixed1), resolucion, 56, 152);
  gtk_widget_set_size_request (resolucion, 40, 24);

  separar = gtk_button_new_with_mnemonic (_("Separar"));
  gtk_widget_show (separar);
  gtk_fixed_put (GTK_FIXED (fixed1), separar, 8, 184);
  gtk_widget_set_size_request (separar, 96, 32);
  gtk_widget_set_sensitive (separar, FALSE);

  label3 = gtk_label_new (_("Valor"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 8, 224);
  gtk_widget_set_size_request (label3, 32, 24);

  label2 = gtk_label_new (_("Umbral"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 104, 224);
  gtk_widget_set_size_request (label2, 48, 24);

  comboColores = gtk_combo_box_new_text ();
  gtk_widget_show (comboColores);
  gtk_fixed_put (GTK_FIXED (fixed1), comboColores, 112, 192);
  gtk_widget_set_size_request (comboColores, 50, 24);

  borrarMaximo = gtk_button_new_with_mnemonic (_("Borrar"));
  gtk_widget_show (borrarMaximo);
  gtk_fixed_put (GTK_FIXED (fixed1), borrarMaximo, 168, 184);
  gtk_widget_set_size_request (borrarMaximo, 48, 32);

  label1 = gtk_label_new (_("Minimo "));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 0, 120);
  gtk_widget_set_size_request (label1, 56, 24);

  label4 = gtk_label_new (_("Distancia"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 0, 152);
  gtk_widget_set_size_request (label4, 56, 24);

  g_signal_connect ((gpointer) window1, "destroy",
                    G_CALLBACK (on_window1_destroy),
                    NULL);
  g_signal_connect ((gpointer) window1, "show",
                    G_CALLBACK (on_window1_show),
                    NULL);
  g_signal_connect ((gpointer) window1, "realize",
                    G_CALLBACK (on_window1_realize),
                    NULL);
  g_signal_connect ((gpointer) histograma, "expose_event",
                    G_CALLBACK (on_histograma_expose_event),
                    NULL);
  g_signal_connect ((gpointer) muestra, "expose_event",
                    G_CALLBACK (on_muestra_expose_event),
                    NULL);
  g_signal_connect ((gpointer) numeroResultado, "value_changed",
                    G_CALLBACK (on_numeroResultado_value_changed),
                    NULL);
  g_signal_connect ((gpointer) verOriginal, "clicked",
                    G_CALLBACK (on_verOriginal_clicked),
                    NULL);
  g_signal_connect ((gpointer) verResultados, "clicked",
                    G_CALLBACK (on_verResultados_clicked),
                    NULL);
  g_signal_connect ((gpointer) matiz, "clicked",
                    G_CALLBACK (on_matiz_clicked),
                    NULL);
  g_signal_connect ((gpointer) saturacion, "clicked",
                    G_CALLBACK (on_saturacion_clicked),
                    NULL);
  g_signal_connect ((gpointer) valor, "clicked",
                    G_CALLBACK (on_valor_clicked),
                    NULL);
  g_signal_connect ((gpointer) valorMaximo, "value_changed",
                    G_CALLBACK (on_valorMaximo_value_changed),
                    NULL);
  g_signal_connect ((gpointer) procesar, "clicked",
                    G_CALLBACK (on_procesar_clicked),
                    NULL);
  g_signal_connect ((gpointer) selectorArchivo, "selection_changed",
                    G_CALLBACK (on_selectorArchivo_selection_changed),
                    NULL);
  g_signal_connect ((gpointer) separar, "clicked",
                    G_CALLBACK (on_separar_clicked),
                    NULL);
  g_signal_connect ((gpointer) borrarMaximo, "clicked",
                    G_CALLBACK (on_borrarMaximo_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (window1, imagen, "imagen");
  GLADE_HOOKUP_OBJECT (window1, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window1, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (window1, histograma, "histograma");
  GLADE_HOOKUP_OBJECT (window1, muestra, "muestra");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, numeroResultado, "numeroResultado");
  GLADE_HOOKUP_OBJECT (window1, minimo, "minimo");
  GLADE_HOOKUP_OBJECT (window1, umbral, "umbral");
  GLADE_HOOKUP_OBJECT (window1, verOriginal, "verOriginal");
  GLADE_HOOKUP_OBJECT (window1, verResultados, "verResultados");
  GLADE_HOOKUP_OBJECT (window1, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (window1, vseparator2, "vseparator2");
  GLADE_HOOKUP_OBJECT (window1, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (window1, matiz, "matiz");
  GLADE_HOOKUP_OBJECT (window1, saturacion, "saturacion");
  GLADE_HOOKUP_OBJECT (window1, valor, "valor");
  GLADE_HOOKUP_OBJECT (window1, valorMaximo, "valorMaximo");
  GLADE_HOOKUP_OBJECT (window1, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (window1, procesar, "procesar");
  GLADE_HOOKUP_OBJECT (window1, selectorArchivo, "selectorArchivo");
  GLADE_HOOKUP_OBJECT (window1, resolucion, "resolucion");
  GLADE_HOOKUP_OBJECT (window1, separar, "separar");
  GLADE_HOOKUP_OBJECT (window1, label3, "label3");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1, comboColores, "comboColores");
  GLADE_HOOKUP_OBJECT (window1, borrarMaximo, "borrarMaximo");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1, label4, "label4");

  return window1;
}

