/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *vbox1;
  GtkWidget *imagen;
  GtkWidget *hbox1;
  GtkWidget *vbox2;
  GtkWidget *histograma;
  GtkWidget *muestra;
  GtkWidget *fixed1;
  GtkObject *numeroResultado_adj;
  GtkWidget *numeroResultado;
  GtkObject *minimo_adj;
  GtkWidget *minimo;
  GtkObject *umbral_adj;
  GtkWidget *umbral;
  GtkObject *valorMaximo_adj;
  GtkWidget *valorMaximo;
  GtkObject *resolucion_adj;
  GtkWidget *resolucion;
  GtkWidget *comboColores;
  GtkWidget *activo;
  GtkWidget *label3;
  GtkWidget *label2;
  GtkWidget *separar;
  GtkWidget *selectorArchivo;
  GtkWidget *label4;
  GtkWidget *label1;
  GtkWidget *procesar;
  GtkWidget *vseparator1;
  GtkWidget *vseparator3;
  GtkWidget *vseparator2;
  GtkWidget *hseparator1;
  GtkWidget *hseparator2;
  GtkWidget *hseparator4;
  GtkWidget *matiz;
  GSList *matiz_group = NULL;
  GtkWidget *saturacion;
  GtkWidget *valor;
  GtkWidget *verOriginal;
  GSList *verOriginal_group = NULL;
  GtkWidget *verResultados;
  GtkWidget *vseparator5;
  GtkWidget *hseparator3;
  GtkObject *numObjeto_adj;
  GtkWidget *numObjeto;
  GtkWidget *segmentar;
  GtkWidget *hseparator5;
  GtkWidget *vseparator7;
  GtkWidget *hseparator7;
  GtkObject *tolAngulo_adj;
  GtkWidget *tolAngulo;
  GtkObject *largoSeg_adj;
  GtkWidget *largoSeg;
  GtkWidget *label6;
  GtkWidget *label7;
  GtkWidget *comparar;
  GtkWidget *estudiarFormas;
  GtkWidget *label5;
  GtkWidget *igualODiferente;
  GtkWidget *forma1;
  GSList *forma1_group = NULL;
  GtkWidget *forma2;
  GtkObject *toleranciaCompara_adj;
  GtkWidget *toleranciaCompara;
  GtkWidget *label8;
  GtkObject *toleranciaComparaAngulo_adj;
  GtkWidget *toleranciaComparaAngulo;
  GtkWidget *label9;
  GtkWidget *label10;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("Proyecto PDI Y\303\255cas"));

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (window1), vbox1);

  imagen = create_pixmap (window1, NULL);
  gtk_widget_show (imagen);
  gtk_box_pack_start (GTK_BOX (vbox1), imagen, TRUE, TRUE, 0);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, TRUE, TRUE, 0);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (hbox1), vbox2, TRUE, TRUE, 0);

  histograma = gtk_drawing_area_new ();
  gtk_widget_show (histograma);
  gtk_box_pack_start (GTK_BOX (vbox2), histograma, TRUE, TRUE, 0);
  gtk_widget_set_size_request (histograma, 360, 100);

  muestra = gtk_drawing_area_new ();
  gtk_widget_show (muestra);
  gtk_box_pack_start (GTK_BOX (vbox2), muestra, TRUE, TRUE, 0);
  gtk_widget_set_size_request (muestra, 360, 10);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_box_pack_start (GTK_BOX (hbox1), fixed1, TRUE, TRUE, 0);

  numeroResultado_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  numeroResultado = gtk_spin_button_new (GTK_ADJUSTMENT (numeroResultado_adj), 1, 0);
  gtk_widget_show (numeroResultado);
  gtk_fixed_put (GTK_FIXED (fixed1), numeroResultado, 176, 8);
  gtk_widget_set_size_request (numeroResultado, 40, 24);
  gtk_widget_set_sensitive (numeroResultado, FALSE);

  minimo_adj = gtk_adjustment_new (10, 0, 100, 1, 10, 10);
  minimo = gtk_spin_button_new (GTK_ADJUSTMENT (minimo_adj), 1, 0);
  gtk_widget_show (minimo);
  gtk_fixed_put (GTK_FIXED (fixed1), minimo, 72, 128);
  gtk_widget_set_size_request (minimo, 40, 24);

  umbral_adj = gtk_adjustment_new (20, 0, 359, 1, 10, 10);
  umbral = gtk_spin_button_new (GTK_ADJUSTMENT (umbral_adj), 1, 0);
  gtk_widget_show (umbral);
  gtk_fixed_put (GTK_FIXED (fixed1), umbral, 288, 120);
  gtk_widget_set_size_request (umbral, 40, 24);
  gtk_widget_set_sensitive (umbral, FALSE);

  valorMaximo_adj = gtk_adjustment_new (0, 0, 359, 1, 10, 10);
  valorMaximo = gtk_spin_button_new (GTK_ADJUSTMENT (valorMaximo_adj), 1, 0);
  gtk_widget_show (valorMaximo);
  gtk_fixed_put (GTK_FIXED (fixed1), valorMaximo, 272, 88);
  gtk_widget_set_size_request (valorMaximo, 56, 24);
  gtk_widget_set_sensitive (valorMaximo, FALSE);

  resolucion_adj = gtk_adjustment_new (10, 1, 100, 1, 10, 10);
  resolucion = gtk_spin_button_new (GTK_ADJUSTMENT (resolucion_adj), 1, 0);
  gtk_widget_show (resolucion);
  gtk_fixed_put (GTK_FIXED (fixed1), resolucion, 72, 160);
  gtk_widget_set_size_request (resolucion, 40, 24);

  comboColores = gtk_combo_box_new_text ();
  gtk_widget_show (comboColores);
  gtk_fixed_put (GTK_FIXED (fixed1), comboColores, 232, 48);
  gtk_widget_set_size_request (comboColores, 56, 32);
  gtk_widget_set_sensitive (comboColores, FALSE);

  activo = gtk_check_button_new_with_mnemonic (_("Activo"));
  gtk_widget_show (activo);
  gtk_fixed_put (GTK_FIXED (fixed1), activo, 288, 48);
  gtk_widget_set_size_request (activo, 64, 24);
  gtk_widget_set_sensitive (activo, FALSE);

  label3 = gtk_label_new (_("Valor"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 232, 88);
  gtk_widget_set_size_request (label3, 32, 24);

  label2 = gtk_label_new (_("Umbral"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 232, 120);
  gtk_widget_set_size_request (label2, 48, 24);

  separar = gtk_button_new_with_mnemonic (_("Separar"));
  gtk_widget_show (separar);
  gtk_fixed_put (GTK_FIXED (fixed1), separar, 232, 8);
  gtk_widget_set_size_request (separar, 96, 32);
  gtk_widget_set_sensitive (separar, FALSE);

  selectorArchivo = gtk_file_chooser_button_new (_("Seleccione un archivo"), GTK_FILE_CHOOSER_ACTION_OPEN);
  gtk_widget_show (selectorArchivo);
  gtk_fixed_put (GTK_FIXED (fixed1), selectorArchivo, 8, 40);
  gtk_widget_set_size_request (selectorArchivo, 208, 32);

  label4 = gtk_label_new (_("Distancia"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 8, 160);
  gtk_widget_set_size_request (label4, 64, 24);

  label1 = gtk_label_new (_("Minimo "));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 8, 128);
  gtk_widget_set_size_request (label1, 56, 24);

  procesar = gtk_button_new_with_mnemonic (_("Analizar"));
  gtk_widget_show (procesar);
  gtk_fixed_put (GTK_FIXED (fixed1), procesar, 8, 88);
  gtk_widget_set_size_request (procesar, 96, 32);
  gtk_widget_set_sensitive (procesar, FALSE);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_fixed_put (GTK_FIXED (fixed1), vseparator1, 112, 88);
  gtk_widget_set_size_request (vseparator1, 16, 73);

  vseparator3 = gtk_vseparator_new ();
  gtk_widget_show (vseparator3);
  gtk_fixed_put (GTK_FIXED (fixed1), vseparator3, 216, 0);
  gtk_widget_set_size_request (vseparator3, 16, 192);

  vseparator2 = gtk_vseparator_new ();
  gtk_widget_show (vseparator2);
  gtk_fixed_put (GTK_FIXED (fixed1), vseparator2, 208, 88);
  gtk_widget_set_size_request (vseparator2, 16, 73);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_fixed_put (GTK_FIXED (fixed1), hseparator1, 120, 152);
  gtk_widget_set_size_request (hseparator1, 97, 16);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_fixed_put (GTK_FIXED (fixed1), hseparator2, 120, 80);
  gtk_widget_set_size_request (hseparator2, 97, 16);

  hseparator4 = gtk_hseparator_new ();
  gtk_widget_show (hseparator4);
  gtk_fixed_put (GTK_FIXED (fixed1), hseparator4, 0, 72);
  gtk_widget_set_size_request (hseparator4, 224, 16);

  matiz = gtk_radio_button_new_with_mnemonic (NULL, _("Matiz"));
  gtk_widget_show (matiz);
  gtk_fixed_put (GTK_FIXED (fixed1), matiz, 120, 88);
  gtk_widget_set_size_request (matiz, 96, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (matiz), matiz_group);
  matiz_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (matiz));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (matiz), TRUE);

  saturacion = gtk_radio_button_new_with_mnemonic (NULL, _("Saturacion"));
  gtk_widget_show (saturacion);
  gtk_fixed_put (GTK_FIXED (fixed1), saturacion, 120, 112);
  gtk_widget_set_size_request (saturacion, 106, 22);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (saturacion), matiz_group);
  matiz_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (saturacion));

  valor = gtk_radio_button_new_with_mnemonic (NULL, _("Valor"));
  gtk_widget_show (valor);
  gtk_fixed_put (GTK_FIXED (fixed1), valor, 120, 136);
  gtk_widget_set_size_request (valor, 88, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (valor), matiz_group);
  matiz_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (valor));

  verOriginal = gtk_radio_button_new_with_mnemonic (NULL, _("Original"));
  gtk_widget_show (verOriginal);
  gtk_fixed_put (GTK_FIXED (fixed1), verOriginal, 8, 8);
  gtk_widget_set_size_request (verOriginal, 106, 22);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (verOriginal), verOriginal_group);
  verOriginal_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (verOriginal));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (verOriginal), TRUE);

  verResultados = gtk_radio_button_new_with_mnemonic (NULL, _("Resultado"));
  gtk_widget_show (verResultados);
  gtk_fixed_put (GTK_FIXED (fixed1), verResultados, 88, 8);
  gtk_widget_set_size_request (verResultados, 88, 24);
  gtk_widget_set_sensitive (verResultados, FALSE);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (verResultados), verOriginal_group);
  verOriginal_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (verResultados));

  vseparator5 = gtk_vseparator_new ();
  gtk_widget_show (vseparator5);
  gtk_fixed_put (GTK_FIXED (fixed1), vseparator5, 352, 0);
  gtk_widget_set_size_request (vseparator5, 16, 152);

  hseparator3 = gtk_hseparator_new ();
  gtk_widget_show (hseparator3);
  gtk_fixed_put (GTK_FIXED (fixed1), hseparator3, 224, 144);
  gtk_widget_set_size_request (hseparator3, 136, 16);

  numObjeto_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  numObjeto = gtk_spin_button_new (GTK_ADJUSTMENT (numObjeto_adj), 1, 0);
  gtk_widget_show (numObjeto);
  gtk_fixed_put (GTK_FIXED (fixed1), numObjeto, 424, 72);
  gtk_widget_set_size_request (numObjeto, 40, 24);
  gtk_widget_set_sensitive (numObjeto, FALSE);

  segmentar = gtk_button_new_with_mnemonic (_("Segmentar"));
  gtk_widget_show (segmentar);
  gtk_fixed_put (GTK_FIXED (fixed1), segmentar, 256, 160);
  gtk_widget_set_size_request (segmentar, 88, 32);
  gtk_widget_set_sensitive (segmentar, FALSE);

  hseparator5 = gtk_hseparator_new ();
  gtk_widget_show (hseparator5);
  gtk_fixed_put (GTK_FIXED (fixed1), hseparator5, 432, 160);
  gtk_widget_set_size_request (hseparator5, 16, 16);

  vseparator7 = gtk_vseparator_new ();
  gtk_widget_show (vseparator7);
  gtk_fixed_put (GTK_FIXED (fixed1), vseparator7, 440, 152);
  gtk_widget_set_size_request (vseparator7, 16, 32);

  hseparator7 = gtk_hseparator_new ();
  gtk_widget_show (hseparator7);
  gtk_fixed_put (GTK_FIXED (fixed1), hseparator7, 448, 176);
  gtk_widget_set_size_request (hseparator7, 72, 16);

  tolAngulo_adj = gtk_adjustment_new (30, 1, 100, 1, 10, 10);
  tolAngulo = gtk_spin_button_new (GTK_ADJUSTMENT (tolAngulo_adj), 1, 0);
  gtk_widget_show (tolAngulo);
  gtk_fixed_put (GTK_FIXED (fixed1), tolAngulo, 496, 32);
  gtk_widget_set_size_request (tolAngulo, 40, 24);

  largoSeg_adj = gtk_adjustment_new (25, 1, 100, 1, 10, 10);
  largoSeg = gtk_spin_button_new (GTK_ADJUSTMENT (largoSeg_adj), 1, 0);
  gtk_widget_show (largoSeg);
  gtk_fixed_put (GTK_FIXED (fixed1), largoSeg, 496, 0);
  gtk_widget_set_size_request (largoSeg, 40, 24);

  label6 = gtk_label_new (_("Tama\303\261o Segmento"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed1), label6, 368, 8);
  gtk_widget_set_size_request (label6, 120, 16);

  label7 = gtk_label_new (_("Tolerancia Angulo"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed1), label7, 368, 40);
  gtk_widget_set_size_request (label7, 120, 16);

  comparar = gtk_button_new_with_mnemonic (_("Comparar"));
  gtk_widget_show (comparar);
  gtk_fixed_put (GTK_FIXED (fixed1), comparar, 368, 152);
  gtk_widget_set_size_request (comparar, 62, 29);

  estudiarFormas = gtk_button_new_with_mnemonic (_("Estudiar"));
  gtk_widget_show (estudiarFormas);
  gtk_fixed_put (GTK_FIXED (fixed1), estudiarFormas, 472, 64);
  gtk_widget_set_size_request (estudiarFormas, 64, 32);
  gtk_widget_set_sensitive (estudiarFormas, FALSE);

  label5 = gtk_label_new (_("Objeto"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed1), label5, 368, 80);
  gtk_widget_set_size_request (label5, 56, 16);

  igualODiferente = gtk_label_new (_("---"));
  gtk_widget_show (igualODiferente);
  gtk_fixed_put (GTK_FIXED (fixed1), igualODiferente, 448, 160);
  gtk_widget_set_size_request (igualODiferente, 72, 16);

  forma1 = gtk_radio_button_new_with_mnemonic (NULL, _("Forma 1"));
  gtk_widget_show (forma1);
  gtk_fixed_put (GTK_FIXED (fixed1), forma1, 368, 104);
  gtk_widget_set_size_request (forma1, 80, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (forma1), forma1_group);
  forma1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (forma1));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (forma1), TRUE);

  forma2 = gtk_radio_button_new_with_mnemonic (NULL, _("Forma 2"));
  gtk_widget_show (forma2);
  gtk_fixed_put (GTK_FIXED (fixed1), forma2, 368, 128);
  gtk_widget_set_size_request (forma2, 80, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (forma2), forma1_group);
  forma1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (forma2));

  toleranciaCompara_adj = gtk_adjustment_new (6, 0, 100, 1, 10, 10);
  toleranciaCompara = gtk_spin_button_new (GTK_ADJUSTMENT (toleranciaCompara_adj), 1, 0);
  gtk_widget_show (toleranciaCompara);
  gtk_fixed_put (GTK_FIXED (fixed1), toleranciaCompara, 496, 104);
  gtk_widget_set_size_request (toleranciaCompara, 40, 24);

  label8 = gtk_label_new (_("+/- 0.0"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed1), label8, 448, 112);
  gtk_widget_set_size_request (label8, 48, 16);

  toleranciaComparaAngulo_adj = gtk_adjustment_new (6, 0, 100, 1, 10, 10);
  toleranciaComparaAngulo = gtk_spin_button_new (GTK_ADJUSTMENT (toleranciaComparaAngulo_adj), 1, 0);
  gtk_widget_show (toleranciaComparaAngulo);
  gtk_fixed_put (GTK_FIXED (fixed1), toleranciaComparaAngulo, 488, 128);
  gtk_widget_set_size_request (toleranciaComparaAngulo, 40, 24);

  label9 = gtk_label_new (_("+/-"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed1), label9, 456, 136);
  gtk_widget_set_size_request (label9, 38, 17);

  label10 = gtk_label_new (_("\302\272"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed1), label10, 528, 128);
  gtk_widget_set_size_request (label10, 16, 16);

  g_signal_connect ((gpointer) window1, "destroy",
                    G_CALLBACK (on_window1_destroy),
                    NULL);
  g_signal_connect ((gpointer) window1, "show",
                    G_CALLBACK (on_window1_show),
                    NULL);
  g_signal_connect ((gpointer) window1, "realize",
                    G_CALLBACK (on_window1_realize),
                    NULL);
  g_signal_connect ((gpointer) histograma, "expose_event",
                    G_CALLBACK (on_histograma_expose_event),
                    NULL);
  g_signal_connect ((gpointer) muestra, "expose_event",
                    G_CALLBACK (on_muestra_expose_event),
                    NULL);
  g_signal_connect ((gpointer) numeroResultado, "value_changed",
                    G_CALLBACK (on_numeroResultado_value_changed),
                    NULL);
  g_signal_connect ((gpointer) umbral, "value_changed",
                    G_CALLBACK (on_umbral_value_changed),
                    NULL);
  g_signal_connect ((gpointer) valorMaximo, "value_changed",
                    G_CALLBACK (on_valorMaximo_value_changed),
                    NULL);
  g_signal_connect ((gpointer) comboColores, "changed",
                    G_CALLBACK (on_comboColores_changed),
                    NULL);
  g_signal_connect ((gpointer) activo, "clicked",
                    G_CALLBACK (on_activo_clicked),
                    NULL);
  g_signal_connect ((gpointer) separar, "clicked",
                    G_CALLBACK (on_separar_clicked),
                    NULL);
  g_signal_connect ((gpointer) selectorArchivo, "selection_changed",
                    G_CALLBACK (on_selectorArchivo_selection_changed),
                    NULL);
  g_signal_connect ((gpointer) procesar, "clicked",
                    G_CALLBACK (on_procesar_clicked),
                    NULL);
  g_signal_connect ((gpointer) matiz, "clicked",
                    G_CALLBACK (on_matiz_clicked),
                    NULL);
  g_signal_connect ((gpointer) saturacion, "clicked",
                    G_CALLBACK (on_saturacion_clicked),
                    NULL);
  g_signal_connect ((gpointer) valor, "clicked",
                    G_CALLBACK (on_valor_clicked),
                    NULL);
  g_signal_connect ((gpointer) verOriginal, "clicked",
                    G_CALLBACK (on_verOriginal_clicked),
                    NULL);
  g_signal_connect ((gpointer) verResultados, "clicked",
                    G_CALLBACK (on_verResultados_clicked),
                    NULL);
  g_signal_connect ((gpointer) numObjeto, "value_changed",
                    G_CALLBACK (on_numObjeto_value_changed),
                    NULL);
  g_signal_connect ((gpointer) segmentar, "clicked",
                    G_CALLBACK (on_segmentar_clicked),
                    NULL);
  g_signal_connect ((gpointer) comparar, "clicked",
                    G_CALLBACK (on_comparar_clicked),
                    NULL);
  g_signal_connect ((gpointer) estudiarFormas, "clicked",
                    G_CALLBACK (on_estudiarFormas_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (window1, imagen, "imagen");
  GLADE_HOOKUP_OBJECT (window1, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window1, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (window1, histograma, "histograma");
  GLADE_HOOKUP_OBJECT (window1, muestra, "muestra");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, numeroResultado, "numeroResultado");
  GLADE_HOOKUP_OBJECT (window1, minimo, "minimo");
  GLADE_HOOKUP_OBJECT (window1, umbral, "umbral");
  GLADE_HOOKUP_OBJECT (window1, valorMaximo, "valorMaximo");
  GLADE_HOOKUP_OBJECT (window1, resolucion, "resolucion");
  GLADE_HOOKUP_OBJECT (window1, comboColores, "comboColores");
  GLADE_HOOKUP_OBJECT (window1, activo, "activo");
  GLADE_HOOKUP_OBJECT (window1, label3, "label3");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1, separar, "separar");
  GLADE_HOOKUP_OBJECT (window1, selectorArchivo, "selectorArchivo");
  GLADE_HOOKUP_OBJECT (window1, label4, "label4");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1, procesar, "procesar");
  GLADE_HOOKUP_OBJECT (window1, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (window1, vseparator3, "vseparator3");
  GLADE_HOOKUP_OBJECT (window1, vseparator2, "vseparator2");
  GLADE_HOOKUP_OBJECT (window1, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (window1, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (window1, hseparator4, "hseparator4");
  GLADE_HOOKUP_OBJECT (window1, matiz, "matiz");
  GLADE_HOOKUP_OBJECT (window1, saturacion, "saturacion");
  GLADE_HOOKUP_OBJECT (window1, valor, "valor");
  GLADE_HOOKUP_OBJECT (window1, verOriginal, "verOriginal");
  GLADE_HOOKUP_OBJECT (window1, verResultados, "verResultados");
  GLADE_HOOKUP_OBJECT (window1, vseparator5, "vseparator5");
  GLADE_HOOKUP_OBJECT (window1, hseparator3, "hseparator3");
  GLADE_HOOKUP_OBJECT (window1, numObjeto, "numObjeto");
  GLADE_HOOKUP_OBJECT (window1, segmentar, "segmentar");
  GLADE_HOOKUP_OBJECT (window1, hseparator5, "hseparator5");
  GLADE_HOOKUP_OBJECT (window1, vseparator7, "vseparator7");
  GLADE_HOOKUP_OBJECT (window1, hseparator7, "hseparator7");
  GLADE_HOOKUP_OBJECT (window1, tolAngulo, "tolAngulo");
  GLADE_HOOKUP_OBJECT (window1, largoSeg, "largoSeg");
  GLADE_HOOKUP_OBJECT (window1, label6, "label6");
  GLADE_HOOKUP_OBJECT (window1, label7, "label7");
  GLADE_HOOKUP_OBJECT (window1, comparar, "comparar");
  GLADE_HOOKUP_OBJECT (window1, estudiarFormas, "estudiarFormas");
  GLADE_HOOKUP_OBJECT (window1, label5, "label5");
  GLADE_HOOKUP_OBJECT (window1, igualODiferente, "igualODiferente");
  GLADE_HOOKUP_OBJECT (window1, forma1, "forma1");
  GLADE_HOOKUP_OBJECT (window1, forma2, "forma2");
  GLADE_HOOKUP_OBJECT (window1, toleranciaCompara, "toleranciaCompara");
  GLADE_HOOKUP_OBJECT (window1, label8, "label8");
  GLADE_HOOKUP_OBJECT (window1, toleranciaComparaAngulo, "toleranciaComparaAngulo");
  GLADE_HOOKUP_OBJECT (window1, label9, "label9");
  GLADE_HOOKUP_OBJECT (window1, label10, "label10");

  return window1;
}

